export const cards = [
  [
    "Action (set A)",
    "Action (set B)",
    "Animal (set A)",
    "Animal (set B)",
    "Clothes",
    "Emotions",
  ],
  [
    {
      word: "cry",
      translation: "ტირილი",
      image: "img/cry.jpg",
      audioSrc: "audio/cry.mp3",
    },
    {
      word: "dance",
      translation: "ცეკვა",
      image: "img/dance.jpg",
      audioSrc: "audio/dance.mp3",
    },
    {
      word: "dive",
      translation: "ყვინთვა",
      image: "img/dive.jpg",
      audioSrc: "audio/dive.mp3",
    },
    {
      word: "draw",
      translation: "ხატვა",
      image: "img/draw.jpg",
      audioSrc: "audio/draw.mp3",
    },
    {
      word: "fish",
      translation: "თევზაობა",
      image: "img/fish.jpg",
      audioSrc: "audio/fish.mp3",
    },
    {
      word: "fly",
      translation: "ფრენა",
      image: "img/fly.jpg",
      audioSrc: "audio/fly.mp3",
    },
    {
      word: "hug",
      translation: "ჩახუტება",
      image: "img/hug.jpg",
      audioSrc: "audio/hug.mp3",
    },
    {
      word: "jump",
      translation: "ხტომა",
      image: "img/jump.jpg",
      audioSrc: "audio/jump.mp3",
    },
  ],
  [
    {
      word: "open",
      translation: "გაღება",
      image: "img/open.jpg",
      audioSrc: "audio/open.mp3",
    },
    {
      word: "play",
      translation: "თამაში",
      image: "img/play.jpg",
      audioSrc: "audio/play.mp3",
    },
    {
      word: "point",
      translation: "ჩვენება",
      image: "img/point.jpg",
      audioSrc: "audio/point.mp3",
    },
    {
      word: "ride",
      translation: "ტარება",
      image: "img/ride.jpg",
      audioSrc: "audio/ride.mp3",
    },
    {
      word: "run",
      translation: "სირბილი",
      image: "img/run.jpg",
      audioSrc: "audio/run.mp3",
    },
    {
      word: "sing",
      translation: "სიმღერა",
      image: "img/sing.jpg",
      audioSrc: "audio/sing.mp3",
    },
    {
      word: "skip",
      translation: "ხტუნვა, ბავშვური",
      image: "img/skip.jpg",
      audioSrc: "audio/skip.mp3",
    },
    {
      word: "swim",
      translation: "ცურვა",
      image: "img/swim.jpg",
      audioSrc: "audio/swim.mp3",
    },
  ],
  [
    {
      word: "cat",
      translation: "კატა",
      image: "img/cat.jpg",
      audioSrc: "audio/cat.mp3",
    },
    {
      word: "chick",
      translation: "წიწილა",
      image: "img/chick.jpg",
      audioSrc: "audio/chick.mp3",
    },
    {
      word: "chicken",
      translation: "ქათამი",
      image: "img/chicken.jpg",
      audioSrc: "audio/chicken.mp3",
    },
    {
      word: "dog",
      translation: "ძაღლი",
      image: "img/dog.jpg",
      audioSrc: "audio/dog.mp3",
    },
    {
      word: "horse",
      translation: "ცხენი",
      image: "img/horse.jpg",
      audioSrc: "audio/horse.mp3",
    },
    {
      word: "pig",
      translation: "ღორი",
      image: "img/pig.jpg",
      audioSrc: "audio/pig.mp3",
    },
    {
      word: "rabbit",
      translation: "კურდღელი",
      image: "img/rabbit.jpg",
      audioSrc: "audio/rabbit.mp3",
    },
    {
      word: "sheep",
      translation: "ცხვარი",
      image: "img/sheep.jpg",
      audioSrc: "audio/sheep.mp3",
    },
  ],
  [
    {
      word: "bird",
      translation: "ჩიტი",
      image: "img/bird.jpg",
      audioSrc: "audio/bird.mp3",
    },
    {
      word: "fish",
      translation: "თევზი",
      image: "img/fish1.jpg",
      audioSrc: "audio/fish.mp3",
    },
    {
      word: "frog",
      translation: "ბაყაყი",
      image: "img/frog.jpg",
      audioSrc: "audio/frog.mp3",
    },
    {
      word: "giraffe",
      translation: "ჟირაფი",
      image: "img/giraffe.jpg",
      audioSrc: "audio/giraffe.mp3",
    },
    {
      word: "lion",
      translation: "ლომი",
      image: "img/lion.jpg",
      audioSrc: "audio/lion.mp3",
    },
    {
      word: "mouse",
      translation: "თაგვი",
      image: "img/mouse.jpg",
      audioSrc: "audio/mouse.mp3",
    },
    {
      word: "turtle",
      translation: "კუ",
      image: "img/turtle.jpg",
      audioSrc: "audio/turtle.mp3",
    },
    {
      word: "dolphin",
      translation: "დელფინი",
      image: "img/dolphin.jpg",
      audioSrc: "audio/dolphin.mp3",
    },
  ],
  [
    {
      word: "skirt",
      translation: "მინიკაბა",
      image: "img/skirt.jpg",
      audioSrc: "audio/skirt.mp3",
    },
    {
      word: "pants",
      translation: "შარვალი",
      image: "img/pants.jpg",
      audioSrc: "audio/pants.mp3",
    },
    {
      word: "blouse",
      translation: "პერანგი",
      image: "img/blouse.jpg",
      audioSrc: "audio/blouse.mp3",
    },
    {
      word: "dress",
      translation: "კაბა",
      image: "img/dress.jpg",
      audioSrc: "audio/dress.mp3",
    },
    {
      word: "boot",
      translation: "ტუფლი",
      image: "img/boot.jpg",
      audioSrc: "audio/boot.mp3",
    },
    {
      word: "shirt",
      translation: "პერანგი",
      image: "img/shirt.jpg",
      audioSrc: "audio/shirt.mp3",
    },
    {
      word: "coat",
      translation: "პალტო",
      image: "img/coat.jpg",
      audioSrc: "audio/coat.mp3",
    },
    {
      word: "shoe",
      translation: "ფეხსაცმელი",
      image: "img/shoe.jpg",
      audioSrc: "audio/shoe.mp3",
    },
  ],
  [
    {
      word: "sad",
      translation: "მოწყენილი",
      image: "img/sad.jpg",
      audioSrc: "audio/sad.mp3",
    },
    {
      word: "angry",
      translation: "გაბრაზებული",
      image: "img/angry.jpg",
      audioSrc: "audio/angry.mp3",
    },
    {
      word: "happy",
      translation: "ბედნიერი",
      image: "img/happy.jpg",
      audioSrc: "audio/happy.mp3",
    },
    {
      word: "tired",
      translation: "დაღლილი",
      image: "img/tired.jpg",
      audioSrc: "audio/tired.mp3",
    },
    {
      word: "surprised",
      translation: "გაკვირვებული",
      image: "img/surprised.jpg",
      audioSrc: "audio/surprised.mp3",
    },
    {
      word: "scared",
      translation: "შეშინებული",
      image: "img/scared.jpg",
      audioSrc: "audio/scared.mp3",
    },
    {
      word: "smile",
      translation: "ღიმილი",
      image: "img/smile.jpg",
      audioSrc: "audio/smile.mp3",
    },
    {
      word: "laugh",
      translation: "სიცილი",
      image: "img/laugh.jpg",
      audioSrc: "audio/laugh.mp3",
    },
  ],
  [
    {
      word: "pluto",
      translation: "პლუტონი",
      image: "img/pluto.jpg",
      audioSrc: "audio/pluto.mp3",
    },
    {
      word: "mars",
      translation: "მარსი",
      image: "img/mars.jpg",
      audioSrc: "audio/mars.mp3",
    },
    {
      word: "jupiter",
      translation: "იუპიტერი",
      image: "img/jupiter.jpg",
      audioSrc: "audio/jupiter.mp3",
    },
    {
      word: "mercury",
      translation: "მერკური",
      image: "img/mercury.jpg",
      audioSrc: "audio/mercury.mp3",
    },
    {
      word: "venus",
      translation: "ვენერა",
      image: "img/venus.jpg",
      audioSrc: "audio/venus.mp3",
    },
    {
      word: "saturn",
      translation: "სატურნი",
      image: "img/saturn.jpg",
      audioSrc: "audio/saturn.mp3",
    },
    {
      word: "uranus",
      translation: "ურანუსი",
      image: "img/uranus.jpg",
      audioSrc: "audio/uranus.mp3",
    },
    {
      word: "neptune",
      translation: "ნეპტუნი",
      image: "img/neptune.jpg",
      audioSrc: "audio/neptune.mp3",
    },
  ],
  [
    {
      word: "friends(r2d2@c3po)",
      translation: " რ2დ2 და ც3პიო",
      image: "img/friends(r2d2@c3po).jpg",
      audioSrc: "audio/friends(r2d2@c3po).mp3",
    },
    {
      word: "dracula",
      translation: "დრაკულა",
      image: "img/dracula.jpg",
      audioSrc: "audio/dracula.mp3",
    },
    {
      word: "darthvader",
      translation: "დართ ვეიდერი",
      image: "img/darthvader.jpg",
      audioSrc: "audio/darthvader.mp3",
    },
    {
      word: "thanos",
      translation: "ტანოსი",
      image: "img/thanos.jpg",
      audioSrc: "audio/thanos.mp3",
    },
    {
      word: "chucky",
      translation: "ჩაკი",
      image: "img/chucky.jpg",
      audioSrc: "audio/chucky.mp3",
    },
    {
      word: "deadpool",
      translation: "დედპული",
      image: "img/deadpool.jpg",
      audioSrc: "audio/deadpool.mp3",
    },
    {
      word: "batman",
      translation: "ბეტმენი",
      image: "img/batman.jpg",
      audioSrc: "audio/batman.mp3",
    },
    {
      word: "minion",
      translation: "მინიონი",
      image: "img/minion.jpg",
      audioSrc: "audio/minion.mp3",
    },
  ],
];
// export default cards2;
